name: midterm
description: Midterm project app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6

  cupertino_icons: ^0.1.0
  shrine_images: 1.1.1

  webview_flutter: 0.3.19+9
  carousel_slider: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/stay.jpg
    - assets/philos.jpg
    - assets/lahan.jpg
    - assets/comodo.jpg
    - assets/hotelview.jpg
    - assets/galaxy.jpg
